### ISSUE TITLE
Aktionen vom Partner-Net abrufen

### ISSUE THREAD

**Issue by SW1605** [NoFear23m/ComplianceManager#11]
Wenn man im Partner-Net in einen Fall öffnet besteht die Möglichkeit bei "Aktionen"  (Bild1) zu sehen was der Großhändler veranlasst hat bzw. mit dem Kunden besprochen hat (Bild2).  Ist es möglich das diese Aktionen auch übernommen werden? Zum Beispiel als 1 großer History Eintrag oder eventuell für jede Aktion ein einzelner Eintrag? 

![29613381-ff3187ee-8805-11e7-9f96-8680e54bdcbc_li](https://user-images.githubusercontent.com/15660141/29614003-beed3edc-8808-11e7-9352-a584e30598d2.jpg)

![29613380-ff307458-8805-11e7-9a14-3fa439ef0c94_li](https://user-images.githubusercontent.com/15660141/29614007-c2d295e2-8808-11e7-9a1e-9fa48d3a3676.jpg)

**Comment by NoFear23m** [comment]
Ja, sicher eine gute Idee.
wie wäre es wenn man unten in der Leiste einen Button hätte welcher nur Aktiv ist wenn man in den Aktionen drinnen ist. Beschriftung z.b. Aktionen holen. Dann werden die Aktionen in den RAM geladen. Und nach dem Abruf der Reklamation wird der Text in einen Historyeintrag zusammengefasst.

**Comment by SW1605** [comment]
Ja genau, so in der Richtung hätt ich mir das vorgestellt.

**Comment by NoFear23m** [comment]
Leider zu aufwendig. Dadurch das dieser Text per Copy&Paste übertragen werden kann rechtfertig die Funktion keine 3-4 stunden Arbeit für die Implementierung. Leider.
