### ISSUE TITLE
Datumsanzeige in Deutsches Format ändern

### ISSUE THREAD

**Issue by SW1605** [NoFear23m/ComplianceManager#6]
In der Reklamations-Detailansicht wird das Datum teilweise noch im Englischen Format angezeigt.

**Comment by NoFear23m** [comment]
In uclCompliantItemDetail.xaml sollte noch Language = 'de-DE' eingetragen werden. 
Prüfen und Updaten
@SW1605 Danke für die Meldung!

**Comment by NoFear23m** [comment]
Wurde geändert - Update ist raus!!! Version 0.0.3.57
