### ISSUE TITLE
Spaltenreihenfolge im Grid speichern und wiederherstellen

### ISSUE THREAD

**Issue by NoFear23m** [NoFear23m/ComplianceManager#7]
In der Liste wäre es super wenn man die Spalten sortieren (geht im Moment auch) und die Sortierung speichern könnte. Beim nächsten Start und beim aktualisieren des Views sollte die Sortierung wieder hergestellt werden.

**Comment by NoFear23m** [comment]
@SW1605 Findest das wäre eine gute Idee??

**Comment by SW1605** [comment]
Gute Idee! Wenn es schon möglich ist die Spalten zu verschieben sollte es auch gespeichert bleiben :)

**Comment by NoFear23m** [comment]
Require two new rows in the database to save the columns width and the columns sortindex to UserSettings.
New usersetting value with title "GridColumnsWidth" and "GridColunsOrder".
Restoring all of these Properties on load and also on View-Refresh. Example: After closing the ComplianteDetailView the ColectionView is updating the data and the view. On this time we must also refresh the orderstate and the widths of the columns.

We also require a fallback to unvisible columns with a minwidth that depends on the default width.

**Comment by NoFear23m** [comment]
Added ColumnsOrder feature. Saving ColumnsOder on DataGrid.Unloaded back to Database.
Do Convert to String and on Load to List(Of String),  Tests are pending.

**Comment by NoFear23m** [comment]
Added ColumnWidths feature. Saving ColumnsWidths on DataGrid.Unloaded back to Database.
Do Convert to String and on Load to List(Of String). Tests are Pending.

@SW1605 Werde morgen das Update machen. Bitte Teste mal ob soweit alles funzt und gib bitte bescheid. Grüße

**Comment by SW1605** [comment]
Funktioniert top!
