### ISSUE TITLE
Fenstergrößen abspeichern und wiederherstellen

### ISSUE THREAD

**Issue by NoFear23m** [NoFear23m/ComplianceManager#9]
Wäre sicher nicht schlecht die Fenstergrößen zu speichern beim schließen.

Wenn der User gerne das Fenster größer hätte stellt dieser die Größe einmalig ein und beim nächsten Start wird das Fenster in der selben Größe und an der selben Position wieder geöffnet.

**Comment by SW1605** [comment]
Wäre toll, da sich das Fenster schon beim öffnen nur sehr klein öffnet.

**Comment by NoFear23m** [comment]
First two Windows has implemented now this feature on nightly build.
Settings windows are pending.

**Comment by NoFear23m** [comment]
@SW1605 Habe nun ein Update raus. Probier mal wie das so geht. Bei ersten Mal geht's hald recht klein auf. Nach dem Einstellen sollte alles bleiben. Auch beim öffnen einer Reklamation.

**Comment by SW1605** [comment]
Funktioniert leider nicht. Fenster öffnen sich immer wieder klein, habe es gerade 3x probiert. 

Egal ob die Anwendung selbst oder auch die Detailansicht. Habe es mit schließen dazwischen und ohne schließen probiert (Detailansicht).

**Comment by NoFear23m** [comment]
Problem gelöst allerdings wird bei maximiertem Fenster nicht der WindowState gespeichert. siehe #12 
Somit closed
